config/routes.rb
# config/routes.rb

Drone::Application.routes.draw do
  root :to => redirect('/roles')

  resources :recruiters, :roles
end # routes

app/models/recruiter.rb
# app/models/recruiter.rb

class Recruiter < ActiveRecord::Base
  # field :agency,       :type => String
  # field :email,        :type => String
  # field :name,         :type => String
  # field :phone_number, :type => String

  has_many :roles

  validates :name, :presence => true
end # class

app/models/role.rb
# app/models/role.rb

class Role < ActiveRecord::Base
  # field :company,        :type => String
  # field :date_submitted, :type => Date
  # field :notes,          :type => String
  # field :title,          :type => String
  # field :url,            :type => String

  belongs_to :recruiter

  validates :company, :presence => true
  validates :title, :presence => true
end # class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recruiters_controller.rb
# app/controllers/recruiters_controller.rb

class RecruitersController < ApplicationController
  before_action :build_resource, :only => %i(new create)
  before_action :load_resource,  :only => %i(show edit update destroy)
  before_action :load_resources, :only => %i(index)

  # POST /recruiters
  def create
    if @recruiter.save
      redirect_to @recruiter
    else
      render :new
    end # if-else
  end # action create

  # DELETE /recruiters/:id
  def destroy
    @recruiter.destroy
    redirect_to recruiters_path
  end # action destroy

  # GET /recruiters/:id/edit
  def edit; end

  # GET /recruiters
  def index; end

  # GET /recruiters/new
  def new; end

  # GET /recruiters/:id
  def show; end

  # PATCH /recruiters/:id
  def update
    if @recruiter.update_attributes recruiter_params
      redirect_to @recruiter
    else
      render :edit
    end # if-else
  end # action patch

  private

  def build_resource
    @recruiter = Recruiter.new recruiter_params
  end # method build_resource

  def load_resource
    @recruiter = Recruiter.find(params[:id])
  end # method load_resource

  def load_resources
    sort_field     = params.fetch(:sort_field, 'name')
    sort_direction = params.fetch(:sort_direction, 'asc').intern
    sort_direction = :asc unless %i(asc desc).include?(sort_direction)

    @recruiters = Recruiter.order(sort_field => sort_direction)
  end # method load_resources

  def recruiter_params
    params.fetch(:recruiter, {}).permit(:name, :agency, :email, :phone_number)
  end # method recruiter_params
end # class

app/controllers/roles_controller.rb
# app/controllers/roles_controller.rb

class RolesController < ApplicationController
  before_action :build_resource,    :only => %i(new create)
  before_action :load_associations, :only => %i(new edit)
  before_action :load_resource,     :only => %i(show edit update destroy)
  before_action :load_resources,    :only => %i(index)

  # POST /roles
  def create
    if @role.save
      redirect_to @role
    else
      render :new
    end # if-else
  end # method create

  # DELETE /roles/:id
  def destroy
    @role.destroy

    redirect_to roles_path
  end # method destroy

  # GET /roles/:id/edit
  def edit; end

  # GET /roles
  def index; end

  # GET /roles/new
  def new; end

  # GET /roles/:id
  def show; end

  # PATCH /roles/:id
  def update
    if @role.update_attributes role_params
      redirect_to @role
    else
      render :edit
    end # if-else
  end # action update

  private

  def build_resource
    @role = Role.new role_params
  end # method build_resource

  def load_associations
    @recruiters = Recruiter.order(:name => :asc)
  end # method load_associations

  def load_resource
    @role = Role.find params[:id]
  end # method load_resource

  def load_resources
    sort_field     = params.fetch(:sort_field, 'date_submitted')
    sort_direction = params.fetch(:sort_direction, 'asc').intern
    sort_direction = :asc unless %i(asc desc).include?(sort_direction)

    @roles = Role.order(sort_field => sort_direction)
  end # method load_resources

  def process_date! hsh
    if hsh.has_key? 'date_submitted(1i)'
      hsh[:date_submitted] = Date.new(*[*1..3].map { |index|
        hsh.delete("date_submitted(#{index}i)").to_i
      }) # end date
    end # if
    hsh
  end # process_date!

  def role_params
    hsh = params.fetch(:role, {}).permit(:company, :title, :date_submitted, :url, :notes, :recruiter_id)
    process_date!(hsh)
  end # method role_params
end # class

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
-# app/views/layouts/application.html.haml

!!!
%html
  %head
    %title Drone
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %p
      = link_to "Roles", roles_path
      |
      = link_to "Recruiters", recruiters_path

    = yield

app/views/recruiters/_form.html.haml
-# app/views/recruiters/_form.html.haml

= form_for recruiter do |form|
  %p
    = form.label :name
    = form.text_field :name

  %p
    = form.label :agency
    = form.text_field :agency

  %p
    = form.label :email
    = form.text_field :email

  %p
    = form.label :phone_number
    = form.text_field :phone_number

  %p
    = link_to "Cancel", roles_path
    = form.submit

app/views/recruiters/edit.html.haml
-# app/views/recruiters/edit.html.haml

%h1 Edit Recruiter

= render :partial => 'form', :locals => { :recruiter => @recruiter }

app/views/recruiters/index.html.haml
-# app/views/recruiters/index.html.haml

%h1 Recruiters

%p= link_to "New Recruiter", new_recruiter_path

= form_tag recruiters_path, :id => 'sort-recruiters', :method => :get do
  %p
    %strong Sort By:
    = select_tag :sort_field, options_for_select([['Name', :name], ['Agency', :agency]], params[:sort_field])
    = select_tag :sort_direction, options_for_select([['Asc', :asc], ['Desc', :desc]], params[:sort_direction])

%table
  %thead
    %tr
      %td Name
      %td Agency
      %td Email
      %td Phone Number
  %tbody
    - if @recruiters.blank?
      %tr
        %td{ :colspan => 4 } There are no recruiters to view.
    - @recruiters.each do |recruiter|
      %tr
        %td= link_to recruiter.name, recruiter
        %td= recruiter.agency
        %td= recruiter.email
        %td= recruiter.phone_number

app/views/recruiters/new.html.haml
-# app/views/recruiters/new.html.haml

%h1 New Recruiter

= render :partial => 'form', :locals => { :recruiter => @recruiter }

app/views/recruiters/show.html.haml
-# app/views/recruiters/show.html.haml

%h1= @recruiter.name

%p
  = link_to "Edit Recruiter", edit_recruiter_path(@recruiter)
  |
  = link_to "Delete Recruiter", @recruiter, :method => :delete

%p
  %strong Agency:
  - if @recruiter.agency.blank?
    (none)
  - else
    = @recruiter.agency

%p
  %strong Email:
  = @recruiter.email

%p
  %strong Phone Number:
  = @recruiter.phone_number

%h2 Roles

%table
  %thead
    %tr
      %td Company
      %td Title
      %td Date Submitted
  %tbody
    - if @recruiter.roles.blank?
      %tr
        %td{ :colspan => 3 } There are no roles to view.
    - @recruiter.roles.each do |role|
      %tr
        %td= link_to role.company, role
        %td= link_to role.title, role
        %td= I18n.l role.date_submitted

%p= link_to "Back to Recruiters", recruiters_path

app/views/roles/_form.html.haml
-# app/views/roles/_form.html.haml

= form_for role do |form|
  %p
    = form.label :company
    = form.text_field :company

  %p
    = form.label :title
    = form.text_field :title

  %p
    = form.label :recruiter
    = form.select :recruiter_id, options_from_collection_for_select(@recruiters, :id, :name), :prompt => ''

  %p
    = form.label :url
    = form.text_field :url

  %p
    = form.label :date_submitted
    = date_select :role, :date_submitted

  %p
    = form.label :notes
    %br
    = form.text_area :notes, :style => 'max-width:600px;width:100%;'

  %p
    = link_to "Cancel", roles_path
    = form.submit

app/views/roles/edit.html.haml
-# app/views/roles/edit.html.haml

%h1 Edit Role

= render :partial => 'form', :locals => { :role => @role }

app/views/roles/index.html.haml
-# app/views/roles/index.html.haml

%h1 Roles

%p= link_to "New Role", new_role_path

= form_tag roles_path, :id => 'sort-roles',:method => :get do
  %p
    %strong Sort By:
    = select_tag :sort_field, options_for_select([['Date Submitted', :date_submitted], ['Company', :company], ['Title', :title]], params[:sort_field])
    = select_tag :sort_direction, options_for_select([['Asc', :asc], ['Desc', :desc]], params[:sort_direction])

%table
  %thead
    %tr
      %td Company
      %td Title
      %td Date Submitted
      %td Recruiter
      %td Agency
  %tbody
    - if @roles.blank?
      %tr
        %td{ :colspan => 5 } There are no roles to view.
    - @roles.each do |role|
      %tr
        %td= link_to role.company, role
        %td= link_to role.title, role
        %td= I18n.l role.date_submitted
        %td= role.recruiter ? link_to(role.recruiter.name, role.recruiter) : ''
        %td= role.recruiter ? role.recruiter.agency : ''

app/views/roles/new.html.haml
-# app/views/roles/new.html.haml

%h1 New Role

= render :partial => 'form', :locals => { :role => @role }

app/views/roles/show.html.haml
-# app/views/roles/show.html.haml

%h1
  = @role.title
  at
  = @role.company

%p
  = link_to "Edit Role", edit_role_path(@role)
  |
  = link_to "Delete Role", @role, :method => :delete

%p
  %strong Date Submitted:
  - if @role.date_submitted.blank?
    (none)
  - else
    = I18n.l @role.date_submitted

%p
  %strong URL:
  - if @role.url.blank?
    (none)
  - else
    = link_to @role.url, @role.url, :target => '_blank'

%p
  %strong Recruiter:
  - unless @role.recruiter.blank?
    = link_to(@role.recruiter.name, @role.recruiter)
    - unless @role.recruiter.agency.blank?
      at
      = @role.recruiter.agency

%p
  %strong Notes:
  %br
  = @role.notes

%p= link_to "Back to Roles", roles_path